import { ColDef } from 'ag-grid-community'

export const columnDefs: ColDef[] = [
  {
    headerName: 'Name',
    field: 'name',
    minWidth: 300,
    width: 200,
    maxWidth: 300,
    checkboxSelection: true,
  },
  { headerName: 'Type', field: 'type', hide: true },
  { headerName: '% TE', field: 'percTE' },
  { headerName: 'ID', field: 'id', hide: true },
  { headerName: 'Input', field: 'input', hide: true },
  { headerName: 'Output', field: 'output', hide: true },
  { headerName: 'Label', field: 'label', hide: true },
  { headerName: 'Eq. Type', field: 'equipmentType' },
  { headerName: 'manufacturer', field: 'manufacturer', hide: true },
  { headerName: 'model', field: 'model', hide: true },
  { headerName: 'modelVersion', field: 'modelVersion', hide: true },
  { headerName: 'yearBuilt', field: 'yearBuilt', hide: true },
  { headerName: 'size', field: 'size', hide: true },
  { headerName: 'sizeUnit', field: 'sizeUnit', hide: true },
  { headerName: '$ value', field: 'value' },
  { headerName: 'latitude', field: 'latitude', hide: true },
  { headerName: 'longitude', field: 'longitude', hide: true },
  { headerName: 'geotagId', field: 'geotagId', hide: true },
  { headerName: 'geotagName', field: 'geotagName', hide: true },
  { headerName: 'X', field: 'x' },
  { headerName: 'Y', field: 'y' },
  { headerName: 'Maitenance', field: 'isMaitenanceSat' },
  { headerName: 'OperatingConditions', field: 'isOperatingConditionsSat' },
  { headerName: 'Environment', field: 'isEnvironmentSat' },
  { headerName: 'Operators', field: 'isOperatorsSat' },
  { headerName: 'History', field: 'isHistorySat' },
  { headerName: 'SafetyDevice', field: 'isSafetyDeviceSat' },
  { headerName: 'ContingencyPlan', field: 'isContingencyPlanSat' },
  { headerName: 'authors', field: 'authors' },
  { headerName: 'viewers', field: 'viewers' },
]
